### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by theshubhamchugh** [frappe/books#1343]
<h2>Description</h2>
fresh install in macbook this frappe software.
Last update form 0.33.* to 0.34.0

<h2>Steps to Reproduce</h2>

<img width="1470" height="956" alt="Image" src="https://github.com/user-attachments/assets/5ea1058b-8daf-438d-80f6-08e9538665da" />

<h2>Info</h2>

**Error**: _TypeError: this.toggleDropdown is not a function_

**Stack**:
```
TypeError: this.toggleDropdown is not a function
    at Proxy.onInput (app://assets/index-DvBFeq9o.js:76:54751)
    at O.onInput.e.<computed>.e.<computed> (app://assets/index-DvBFeq9o.js:76:55890)
    at Kr (app://assets/index-DvBFeq9o.js:5:656)
    at ws (app://assets/index-DvBFeq9o.js:5:735)
    at HTMLInputElement.n (app://assets/index-DvBFeq9o.js:5:57630)
```

**Version**: `0.34.0`
**Platform**: `darwin`
**Path**: `/edit/JournalEntry/New Journal Entry 05`
**Language**: `English`
**Country**: `in`

<details>
<summary><strong>Feature Flags</strong></summary>

**Accounting Settings**:
```json
{
  "enableDiscounting": false,
  "enableInventory": false,
  "enablePriceList": false,
  "enableInvoiceReturns": false,
  "enableFormCustomization": false,
  "enableERPNextSync": false,
  "enableLead": false,
  "enablePricingRule": false,
  "enableItemEnquiry": false,
  "enableLoyaltyProgram": false,
  "enableCouponCode": false,
  "enableitemGroup": false,
  "enablePointOfSaleWithOutInventory": false,
  "enablePartialPayment": false
}
```

**POS Settings**:
```json
{
  "weightEnabledBarcode": false,
  "canChangeRate": false,
  "hideUnavailableItems": false,
  "canEditDiscount": false,
  "ignorePricingRule": false
}
```

**Inventory Settings**:
```json
{
  "enablePointOfSale": false
}
```

</details>

**Comment by Gadha2311** [comment]
We couldn’t reproduce this issue after upgrading from 0.33. to 0.34.0*. Could you confirm if you performed any additional steps or custom changes before it occurred?

**Comment by shruko** [comment]
I didn’t make any custom changes. I had just installed Frappe Books fresh, and the very next day I saw an update available, so I updated it. After that I started getting this TypeError issue randomly, not every time, but it still shows up sometimes. I’m not sure why it’s happening.

**Comment by abizer-s** [comment]
Happening with me as well, unable to work with Frappe books, was trying to add a new Sales Invoice but it is unable to read the existing sales items and keeps giving this error.

<img width="1440" height="900" alt="Image" src="https://github.com/user-attachments/assets/81f4e40c-930e-4344-bffc-9ec1df08d8e1" />
<img width="1440" height="900" alt="Image" src="https://github.com/user-attachments/assets/fdf82ffd-a37b-47e6-880b-a6e24bc29181" />

**Comment by abizer-s** [comment]
Hi @Gadha2311 
Can we please take up this issue for resolution, mine is an existing setup with lots of data for a small shop and it started happening after auto updating to 0.34. This is happening on a Mac

**Comment by Gadha2311** [comment]
I tested this on a Mac by making a build in v0.33 and then upgrading it to v0.34 using the demo database, but I wasn’t able to reproduce the issue. Could you please confirm if you followed any additional steps in between or if there are specific actions that consistently trigger the error? This will help us investigate further.

**Comment by abizer-s** [comment]
Hi @Gadha2311 
Thank you for looking into this problem, I don't build Frappe from source, I'm using it as-is, there are no other steps I perform; I'm using Frappe books as an end Customer managing accounts, sales and purchases.

I have created a short video of the problem, please refer from 1:00 minute mark and the problem starts occurring.

https://github.com/user-attachments/assets/87f74dd8-250a-4b63-8289-0eac4bacb77c

**Comment by Gadha2311** [comment]
Resolved in [#1367 ](https://github.com/frappe/books/pull/1367m)which will be available in v0.35.0.

**Comment by abizer-s** [comment]
thanks @Gadha2311 ; will be eagerly awaiting the new release
